title: Intently NLU Docs
description: Documentation for the Intently NLU library.
repository: encrystudio/intently-nlu
theme: "just-the-docs"

search_enabled: true
enable_copy_code_button: true
heading_anchors: true
nav_enabled: true
nav_error_report: true

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Intently NLU"
last_edit_timestamp: true

gh_edit_link: false

color_scheme: dark

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
